### ISSUE TITLE
Data Export

### ISSUE THREAD

**Issue by ainsleybernard** [tc-ca/alexa-gc-recalls#1]

**Comment by ainsleybernard** [comment]
Hi @hamjer  , Because all models including vehicles, tires and child restraints are in one table I need to find models that have been recalled as category type = car and suv to filter out non vehicle makes and models.

Should the category type also include motorcycle? And should any other categories be included that I've missed?

See attachment. Thanks!

[vrdb_tt010_categor_table_Exportt.xlsx](https://github.com/tc-ca/alexa-gc-recalls/files/2516678/vrdb_tt010_categor_table_Exportt.xlsx)

**Comment by ainsleybernard** [comment]
Please review export on google drive.

**Comment by hamjer** [comment]
@ainsleybernard  redo export to add other categories
