### ISSUE TITLE
Set up TravisCI

### ISSUE THREAD

**Issue by thomasgohard** [tc-ca/alexa-gc-recalls#29]
- [x] Sign up for and authorise TravisCI
- [ ] Turn on TravisCI on the repository
- [ ] Build .travis.yml configuration script

**Comment by ainsleybernard** [comment]
Repo is in sync with Travis CI using the older platform on travisci.org versus travisci.com
Could not find TC organization/ repo on the travisci.com. Nonetheless looks like the platform will transition legacy setup to the new domain. For more info check https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg
