### ISSUE TITLE
Create repository for synonyms

### ISSUE THREAD

**Issue by thomasgohard** [tc-ca/alexa-gc-recalls#44]
Naming pattern: alexa-gc-recalls-synonyms
Contents: Synonyms of various text strings, in the format needed by Alexa

**Comment by ainsleybernard** [comment]
Created repository, can be found here. https://github.com/tc-ca/alexa-gc-recalls-training-data
Named it training data because it will include slots values which by definition include, canonical value, id, and synonyms.
