### ISSUE TITLE
What Categories Type should be included

### ISSUE THREAD

**Issue by ainsleybernard** [tc-ca/alexa-gc-recalls#8]
Hi @hamjer  , Because all models including vehicles, tires and child restraints are in one table I need to find models that have been recalled as category type = car and suv to filter out non vehicle makes and models.
Should the category type also include motorcycle? And should any other categories be included that I've missed?

See attachment. Thanks!

[vrdb_tt010_categor_table_Exportt.xlsx](https://github.com/tc-ca/alexa-gc-recalls/files/2516678/vrdb_tt010_categor_table_Exportt.xlsx)

_Originally posted by @ainsleybernard in https://github.com/tc-ca/alexa-gc-recalls/issues/1#issuecomment-433200962_

**Comment by ainsleybernard** [comment]
@hamjer I like the idea of "creating a larger list (a list of all vehicles) then narrow the types" down. The only issue is the database is not very supportive. My original exported results would have excluded category types because as you know the type describes the recall and not the models themselves.

I can pull back the category type but the list will appear to have duplicates like the following:

![image](https://user-images.githubusercontent.com/17305314/47661315-2eedf680-db6f-11e8-83b0-bf73c476c7cd.png)

BMW Z4 is categorized as CAR & SUV in one row and in the next row just CAR.
Basically means that one point in time two recalls were issued for this model and the recall applied to different categories.

Do you want to go through the data with these types of duplication, would it be beneficial or slow you down.

The amount of records retrieved would be 9072 (with category type exported)
versus 
6791 (without category type exported) 
excluding the following types CCS, TWC, -9999, EQU, TIR, BS, SW


if we narrow to just MV, CAR, LTV and SUV.
The list is 2354 records  (with category type exported)
versus
1076 records (without category type exported)

This is base query would be used to retrieve the another data exports required.

Let me know what you think, thanks!

**Comment by ainsleybernard** [comment]
Also to note for the above results I'm pulling recalls starting from year 2000 as we talked about during the sprint planning.

**Comment by hamjer** [comment]
@ainsleybernard 

Ok, so I think we should export all except the following fields (I added TWC back in)
CCS
-9999
EQU
TIR
BS
SW

I may have to give you a call to discuss this further. If I got it right...if we don't separate out category type, we end up with some duplicates, but this probably isn't a problem, because EQU, TiR, CCS, BS and SW would never appear in the list...filtering out their models.

**Comment by ainsleybernard** [comment]
@hamjer Yup, if we want to see the category type in the export, you will see duplicates as shown in the above screenshot with the BMW Z4 example.

**Comment by ainsleybernard** [comment]
Ignore the above. Wasn't thinking straight. I've collapse the results so you now the export will have one model, make, manufacturer no matter the various categories it was involved in.

![image](https://user-images.githubusercontent.com/17305314/47730910-85276c00-dc39-11e8-9a72-f7b3ce71990a.png)

will let you know when everything is posted to google drive for your review.

Thanks
